### ISSUE TITLE
Format the payment page

### ISSUE THREAD

**Issue by davidgatti** [0x4447/contract.0x4447.com#2]
If you visit the page with this ID: https://contract.0x4447.com/?id=13123123123, then data will be pulled from the DDB, and the page will have all the info. Now personally I don't have a good vision for now how to organize the information on this page. Take a swing and see what you come up with :)

**Comment by radiantdinosaurs** [comment]
<img width="1362" alt="screen shot 2018-09-19 at 11 16 22 am" src="https://user-images.githubusercontent.com/8292853/45772790-7e024c80-bbfd-11e8-908b-08f0352492ff.png">
<img width="1364" alt="screen shot 2018-09-19 at 11 06 07 am" src="https://user-images.githubusercontent.com/8292853/45772291-14357300-bbfc-11e8-8b42-f3c5a42e756c.png">

These are the two I came up with. The first one is _very_ simple -- keeps the original design and just puts the information into a table. The second one is styled like a classic payment page. It uses disabled input for all the fields (except the credit card). I prefer the second one, myself, but let me know which one you would like to keep or if you want something entirely different.
