### ISSUE TITLE
Add Fullstory support

### ISSUE THREAD

**Issue by davidgatti** [0x4447/contract.0x4447.com#24]
Time to add also Fullstory support. This is the snippet to add to the `_frame.html` file:

```
<script>
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_org'] = 'FAHFR';
window['_fs_namespace'] = 'FS';
(function(m,n,e,t,l,o,g,y){
    if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
    g=m[e]=function(a,b){g.q?g.q.push([a,b]):g._api(a,b);};g.q=[];
    o=n.createElement(t);o.async=1;o.src='https://'+_fs_host+'/s/fs.js';
    y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
    g.identify=function(i,v){g(l,{uid:i});if(v)g(l,v)};g.setUserVars=function(v){g(l,v)};g.event=function(i,v){g('event',{n:i,p:v})};
    g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
    g.consent=function(a){g("consent",!arguments.length||a)};
    g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
    g.clearUserCookie=function(){};
})(window,document,window['_fs_namespace'],'script','user');
</script>
```

And we want also to send the User ID with their name. Check the doc how to do that here: https://help.fullstory.com/develop-js/137379

**Comment by radiantdinosaurs** [comment]
I'm a little lost on this one, because I've never worked with FullStory before. Is the `FS.identify` put outside of that script, in the `_frame`, or on every relevant page (maybe after a DDB query)? And, the `uid` is the `id` we use in the `query_obj`?

Also, wanted to note that FullStory is blocked as a whole on Firefox for tracking protection. So, it seems like it'll only work on Chrome and other browsers that don't give automatic tracking protection.

**Comment by davidgatti** [comment]
When it comes to Firefox, then who cares, we have no control over that, and that is why I don't pay for it and I just use the free version :) 

Only because you never worked doesn't mean you can't do it :). Since we want to record interactions on each page, this snippet needs to be added in the `_frame` bellow the footer. 

The `FS.identify(uid)` for sure we call it once the data from the DB gets back.

**Comment by radiantdinosaurs** [comment]
I went ahead and took a shot at it, let me know if there's anything I should change. I put the `FS.identify` method after each `DDB.get` query. I wasn't sure if this was the best way, or if we should make a single `DDB.get` query in `_frame` and call the method there. Like it said in the documentation, precautions have to be taken to make sure we're calling the method only when we have a `uid`.
