### ISSUE TITLE
Add a Info page

### ISSUE THREAD

**Issue by davidgatti** [0x4447/contract.0x4447.com#9]
We need to add a `info.html` page, that will shown, when someone visits the page, and there is no ID in the URL. I'll add the text, but the page will inform the visitor, that if they want a contract with us, then they have to get in touch with us.

**Steps**

1. Detect that there is no ID
1. redirect the user to the info page by replacing the URL on the page, so they can't hit the back button and go back to the home page, which then will redirect them back to the info page, so there is no endless loop

This check needs to be done on the `_frame` file so it will apply on each page, but there needs to be an expiation for the info page.

**Comment by radiantdinosaurs** [comment]
I'll finish this up once we merge issue #4, so I can make everything work together.

**Comment by radiantdinosaurs** [comment]
Waiting for merge of issue #4 before finishing this up, so I can get the session storage working properly with the Info page.

**Comment by radiantdinosaurs** [comment]
Sounds good, I'll keep that in mind for the future.

About the Navbar on the Info page -- we can always add different content/links to it or just keep it removed entirely. The possibilities are endless. Let me know what you want to do.
